"""
Regime-Filtered Trading Strategy.

Integrates direction, vol_regime, and trend_regime model predictions
to only trade in statistically profitable regime combinations.

Key Finding (8h timeframe):
- Vol=0 (low volatility) + Trend=1 (trending) → 67.5% direction accuracy
- With TP=50bps, SL=30bps: +16.1 bps gross, +6.1 bps net (after 10bps fees)
- P-value: 0.004 (statistically significant)

Usage:
    strategy = RegimeFilteredStrategy()
    signal = strategy.generate_signal(predictions)
    if signal.should_trade:
        entry = strategy.create_entry(signal, current_price)
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

import numpy as np


class Direction(Enum):
    """Trade direction."""

    LONG = 1
    SHORT = -1
    FLAT = 0


class VolRegime(Enum):
    """Volatility regime from vol_regime model."""

    LOW = 0  # Best for trading
    NORMAL = 1  # Moderate
    HIGH = 2  # Avoid trading


class TrendRegime(Enum):
    """Trend regime from trend_regime model."""

    RANGING = 0  # Mean-reverting, avoid
    TRENDING = 1  # Trending, best for direction model


@dataclass
class ModelPredictions:
    """Container for all model predictions at a given timestamp."""

    timestamp: datetime

    # Direction model
    direction_pred: int  # 0=down, 1=up
    direction_prob: float  # Probability of predicted class

    # Vol regime model
    vol_regime_pred: int  # 0=low, 1=normal, 2=high
    vol_regime_prob: float

    # Trend regime model
    trend_regime_pred: int  # 0=ranging, 1=trending
    trend_regime_prob: float

    # Optional: conformal prediction uncertainty
    direction_uncertainty: float | None = None

    def __post_init__(self):
        """Validate predictions."""
        if self.direction_pred not in [0, 1]:
            raise ValueError(
                f"direction_pred must be 0 or 1, got {self.direction_pred}"
            )
        if self.vol_regime_pred not in [0, 1, 2]:
            raise ValueError(
                f"vol_regime_pred must be 0, 1, or 2, got {self.vol_regime_pred}"
            )
        if self.trend_regime_pred not in [0, 1]:
            raise ValueError(
                f"trend_regime_pred must be 0 or 1, got {self.trend_regime_pred}"
            )


@dataclass
class TradeSignal:
    """Signal generated by the strategy."""

    timestamp: datetime
    should_trade: bool
    direction: Direction
    confidence: float  # 0-1, based on model probabilities

    # Regime context
    vol_regime: VolRegime
    trend_regime: TrendRegime

    # Reasoning
    reason: str

    # Risk parameters (from research)
    take_profit_bps: float = 50.0
    stop_loss_bps: float = 30.0

    # Position sizing suggestion (0-1)
    position_size_factor: float = 1.0


@dataclass
class EntryOrder:
    """Entry order with TP/SL levels."""

    timestamp: datetime
    direction: Direction
    entry_price: float
    take_profit_price: float
    stop_loss_price: float
    position_size_factor: float
    signal: TradeSignal

    @property
    def tp_distance_bps(self) -> float:
        """Distance to TP in bps."""
        return abs(self.take_profit_price / self.entry_price - 1) * 10000

    @property
    def sl_distance_bps(self) -> float:
        """Distance to SL in bps."""
        return abs(self.stop_loss_price / self.entry_price - 1) * 10000


@dataclass
class RegimeFilterConfig:
    """Configuration for regime filtering."""

    # Optimal regime combination (from research)
    optimal_vol_regimes: set = field(default_factory=lambda: {0})  # Low vol only
    optimal_trend_regimes: set = field(default_factory=lambda: {1})  # Trending only

    # TP/SL parameters (from optimization)
    take_profit_bps: float = 50.0
    stop_loss_bps: float = 30.0

    # Minimum confidence thresholds
    min_direction_prob: float = 0.50  # Model outputs
    min_vol_regime_prob: float = 0.60  # Vol model is 80% accurate
    min_trend_regime_prob: float = 0.55  # Trend model is 66% accurate

    # Position sizing based on confidence
    use_confidence_sizing: bool = True
    min_size_factor: float = 0.5
    max_size_factor: float = 1.0

    # Additional filters
    max_uncertainty: float | None = None  # From conformal prediction

    # Transaction costs for break-even calculation
    transaction_cost_bps: float = 10.0  # Maker fees


class RegimeFilteredStrategy:
    """
    Strategy that filters trades based on regime predictions.

    Only trades when:
    1. Vol regime = 0 (low volatility predicted)
    2. Trend regime = 1 (trending market predicted)
    3. All model probabilities meet minimum thresholds

    Research results (8h bars, 40 samples):
    - Direction accuracy: 67.5% in optimal regime
    - With TP=50/SL=30: +16.1 bps gross, +6.1 bps net
    - Win rate: 65%
    - P-value: 0.004
    """

    def __init__(self, config: RegimeFilterConfig | None = None):
        """Initialize strategy with config."""
        self.config = config or RegimeFilterConfig()

        # Statistics tracking
        self.signals_generated = 0
        self.trades_taken = 0
        self.trades_skipped = 0

    def generate_signal(self, predictions: ModelPredictions) -> TradeSignal:
        """
        Generate a trade signal based on model predictions.

        Args:
            predictions: Container with all model predictions

        Returns:
            TradeSignal with trade decision and parameters
        """
        self.signals_generated += 1

        # Check regime filters
        vol_regime = VolRegime(predictions.vol_regime_pred)
        trend_regime = TrendRegime(predictions.trend_regime_pred)

        # Determine if in optimal regime
        in_optimal_vol = predictions.vol_regime_pred in self.config.optimal_vol_regimes
        in_optimal_trend = (
            predictions.trend_regime_pred in self.config.optimal_trend_regimes
        )

        # Check probability thresholds
        direction_conf_ok = predictions.direction_prob >= self.config.min_direction_prob
        vol_conf_ok = predictions.vol_regime_prob >= self.config.min_vol_regime_prob
        trend_conf_ok = (
            predictions.trend_regime_prob >= self.config.min_trend_regime_prob
        )

        # Check uncertainty if available
        uncertainty_ok = True
        if self.config.max_uncertainty and predictions.direction_uncertainty:
            uncertainty_ok = (
                predictions.direction_uncertainty <= self.config.max_uncertainty
            )

        # Determine if we should trade
        should_trade = all(
            [
                in_optimal_vol,
                in_optimal_trend,
                direction_conf_ok,
                vol_conf_ok,
                trend_conf_ok,
                uncertainty_ok,
            ]
        )

        # Build reason string
        reasons = []
        if not in_optimal_vol:
            reasons.append(
                f"vol_regime={predictions.vol_regime_pred} not in {self.config.optimal_vol_regimes}"
            )
        if not in_optimal_trend:
            reasons.append(
                f"trend_regime={predictions.trend_regime_pred} not in {self.config.optimal_trend_regimes}"
            )
        if not direction_conf_ok:
            reasons.append(
                f"direction_prob={predictions.direction_prob:.2f} < {self.config.min_direction_prob}"
            )
        if not vol_conf_ok:
            reasons.append(
                f"vol_regime_prob={predictions.vol_regime_prob:.2f} < {self.config.min_vol_regime_prob}"
            )
        if not trend_conf_ok:
            reasons.append(
                f"trend_regime_prob={predictions.trend_regime_prob:.2f} < {self.config.min_trend_regime_prob}"
            )
        if not uncertainty_ok:
            reasons.append(
                f"uncertainty={predictions.direction_uncertainty:.2f} > {self.config.max_uncertainty}"
            )

        if should_trade:
            reason = "Optimal regime: Vol=Low, Trend=Trending"
            self.trades_taken += 1
        else:
            reason = "Filtered: " + "; ".join(reasons)
            self.trades_skipped += 1

        # Determine direction
        if predictions.direction_pred == 1:
            direction = Direction.LONG
        else:
            direction = Direction.SHORT

        # Calculate confidence (geometric mean of probabilities)
        confidence = (
            predictions.direction_prob
            * predictions.vol_regime_prob
            * predictions.trend_regime_prob
        ) ** (1 / 3)

        # Calculate position size factor based on confidence
        if self.config.use_confidence_sizing and should_trade:
            # Scale between min and max based on confidence
            size_range = self.config.max_size_factor - self.config.min_size_factor
            position_size_factor = self.config.min_size_factor + (
                confidence * size_range
            )
        else:
            position_size_factor = 1.0 if should_trade else 0.0

        return TradeSignal(
            timestamp=predictions.timestamp,
            should_trade=should_trade,
            direction=direction if should_trade else Direction.FLAT,
            confidence=confidence,
            vol_regime=vol_regime,
            trend_regime=trend_regime,
            reason=reason,
            take_profit_bps=self.config.take_profit_bps,
            stop_loss_bps=self.config.stop_loss_bps,
            position_size_factor=position_size_factor,
        )

    def create_entry(
        self, signal: TradeSignal, current_price: float
    ) -> EntryOrder | None:
        """
        Create an entry order with TP/SL levels.

        Args:
            signal: Trade signal from generate_signal()
            current_price: Current market price for entry

        Returns:
            EntryOrder if should_trade, else None
        """
        if not signal.should_trade:
            return None

        # Calculate TP/SL prices
        tp_multiplier = signal.take_profit_bps / 10000
        sl_multiplier = signal.stop_loss_bps / 10000

        if signal.direction == Direction.LONG:
            take_profit_price = current_price * (1 + tp_multiplier)
            stop_loss_price = current_price * (1 - sl_multiplier)
        else:  # SHORT
            take_profit_price = current_price * (1 - tp_multiplier)
            stop_loss_price = current_price * (1 + sl_multiplier)

        return EntryOrder(
            timestamp=signal.timestamp,
            direction=signal.direction,
            entry_price=current_price,
            take_profit_price=take_profit_price,
            stop_loss_price=stop_loss_price,
            position_size_factor=signal.position_size_factor,
            signal=signal,
        )

    def check_exit(
        self, entry: EntryOrder, high: float, low: float, close: float
    ) -> tuple[bool, float, str]:
        """
        Check if TP or SL was hit during a bar.

        Args:
            entry: The entry order
            high: Bar high price
            low: Bar low price
            close: Bar close price

        Returns:
            Tuple of (exited, exit_price, exit_reason)
        """
        if entry.direction == Direction.LONG:
            # Check TP first (hit on high)
            if high >= entry.take_profit_price:
                return True, entry.take_profit_price, "TP_HIT"
            # Check SL (hit on low)
            if low <= entry.stop_loss_price:
                return True, entry.stop_loss_price, "SL_HIT"
        else:  # SHORT
            # Check TP first (hit on low)
            if low <= entry.take_profit_price:
                return True, entry.take_profit_price, "TP_HIT"
            # Check SL (hit on high)
            if high >= entry.stop_loss_price:
                return True, entry.stop_loss_price, "SL_HIT"

        return False, close, "HOLDING"

    def calculate_pnl(
        self, entry: EntryOrder, exit_price: float, include_costs: bool = True
    ) -> float:
        """
        Calculate PnL in bps.

        Args:
            entry: Entry order
            exit_price: Exit price
            include_costs: Whether to subtract transaction costs

        Returns:
            PnL in basis points
        """
        if entry.direction == Direction.LONG:
            pnl_bps = (exit_price / entry.entry_price - 1) * 10000
        else:
            pnl_bps = (entry.entry_price / exit_price - 1) * 10000

        if include_costs:
            pnl_bps -= self.config.transaction_cost_bps

        return pnl_bps

    def get_stats(self) -> dict:
        """Get strategy statistics."""
        total = self.signals_generated
        return {
            "signals_generated": total,
            "trades_taken": self.trades_taken,
            "trades_skipped": self.trades_skipped,
            "trade_rate": self.trades_taken / total if total > 0 else 0,
            "filter_rate": self.trades_skipped / total if total > 0 else 0,
        }

    def reset_stats(self):
        """Reset statistics."""
        self.signals_generated = 0
        self.trades_taken = 0
        self.trades_skipped = 0


@dataclass
class AdvancedRegimeConfig(RegimeFilterConfig):
    """
    Extended configuration with additional regime combinations.

    Research found these regime combinations have potential edge:
    - Vol=0, Trend=1: +16.1 bps gross (primary)
    - Vol=1, Trend=1: +8.7 bps gross (secondary, with TP=30)
    """

    # Allow multiple regime combinations with different parameters
    regime_configs: dict = field(
        default_factory=lambda: {
            # Primary: Low vol + Trending
            (0, 1): {"tp_bps": 50, "sl_bps": 30, "size_factor": 1.0},
            # Secondary: Normal vol + Trending (more conservative)
            # (1, 1): {"tp_bps": 30, "sl_bps": 30, "size_factor": 0.5},
        }
    )


class AdvancedRegimeStrategy(RegimeFilteredStrategy):
    """
    Advanced strategy with multiple regime configurations.

    Can trade different regime combinations with different parameters.
    """

    def __init__(self, config: AdvancedRegimeConfig | None = None):
        """Initialize with advanced config."""
        self.adv_config = config or AdvancedRegimeConfig()
        super().__init__(self.adv_config)

    def generate_signal(self, predictions: ModelPredictions) -> TradeSignal:
        """
        Generate signal with regime-specific parameters.
        """
        self.signals_generated += 1

        vol_regime = VolRegime(predictions.vol_regime_pred)
        trend_regime = TrendRegime(predictions.trend_regime_pred)

        # Check if current regime is in our tradeable combinations
        regime_key = (predictions.vol_regime_pred, predictions.trend_regime_pred)

        if regime_key in self.adv_config.regime_configs:
            regime_params = self.adv_config.regime_configs[regime_key]

            # Check probability thresholds
            probs_ok = all(
                [
                    predictions.direction_prob >= self.adv_config.min_direction_prob,
                    predictions.vol_regime_prob >= self.adv_config.min_vol_regime_prob,
                    predictions.trend_regime_prob
                    >= self.adv_config.min_trend_regime_prob,
                ]
            )

            if probs_ok:
                self.trades_taken += 1
                direction = (
                    Direction.LONG
                    if predictions.direction_pred == 1
                    else Direction.SHORT
                )

                confidence = (
                    predictions.direction_prob
                    * predictions.vol_regime_prob
                    * predictions.trend_regime_prob
                ) ** (1 / 3)

                return TradeSignal(
                    timestamp=predictions.timestamp,
                    should_trade=True,
                    direction=direction,
                    confidence=confidence,
                    vol_regime=vol_regime,
                    trend_regime=trend_regime,
                    reason=f"Regime ({regime_key[0]}, {regime_key[1]}): tradeable",
                    take_profit_bps=regime_params["tp_bps"],
                    stop_loss_bps=regime_params["sl_bps"],
                    position_size_factor=regime_params["size_factor"],
                )

        # Not a tradeable regime
        self.trades_skipped += 1
        return TradeSignal(
            timestamp=predictions.timestamp,
            should_trade=False,
            direction=Direction.FLAT,
            confidence=0.0,
            vol_regime=vol_regime,
            trend_regime=trend_regime,
            reason=f"Regime ({predictions.vol_regime_pred}, {predictions.trend_regime_pred}): not tradeable",
            take_profit_bps=0,
            stop_loss_bps=0,
            position_size_factor=0.0,
        )


def backtest_strategy(
    strategy: RegimeFilteredStrategy, predictions_df, ohlc_df, verbose: bool = False
) -> dict:
    """
    Backtest the strategy on historical data.

    Args:
        strategy: Strategy instance
        predictions_df: DataFrame with model predictions
        ohlc_df: DataFrame with OHLC data
        verbose: Print trade details

    Returns:
        Dict with backtest results
    """
    import pandas as pd

    trades = []

    for _, row in predictions_df.iterrows():
        # Create predictions object
        preds = ModelPredictions(
            timestamp=row["timestamp"],
            direction_pred=int(row["dir_pred"]),
            direction_prob=row.get("dir_prob", 0.6),
            vol_regime_pred=int(row["vol_pred"]),
            vol_regime_prob=row.get("vol_prob", 0.8),
            trend_regime_pred=int(row["trend_pred"]),
            trend_regime_prob=row.get("trend_prob", 0.7),
        )

        # Generate signal
        signal = strategy.generate_signal(preds)

        if not signal.should_trade:
            continue

        # Get next bar's OHLC
        next_ts = row["timestamp"] + pd.Timedelta(hours=8)
        next_bar = ohlc_df[ohlc_df.index == next_ts]

        if len(next_bar) == 0:
            continue

        next_bar = next_bar.iloc[0]
        entry_price = next_bar["open"]

        # Create entry order
        entry = strategy.create_entry(signal, entry_price)

        # Check exit
        exited, exit_price, exit_reason = strategy.check_exit(
            entry, next_bar["high"], next_bar["low"], next_bar["close"]
        )

        # Calculate PnL
        pnl_bps = strategy.calculate_pnl(entry, exit_price, include_costs=True)

        trades.append(
            {
                "timestamp": row["timestamp"],
                "direction": signal.direction.name,
                "entry_price": entry_price,
                "exit_price": exit_price,
                "exit_reason": exit_reason,
                "pnl_bps": pnl_bps,
                "vol_regime": signal.vol_regime.value,
                "trend_regime": signal.trend_regime.value,
            }
        )

        if verbose:
            print(
                f"{row['timestamp']}: {signal.direction.name} @ {entry_price:.2f} -> "
                f"{exit_price:.2f} ({exit_reason}): {pnl_bps:+.1f} bps"
            )

    # Calculate metrics
    if not trades:
        return {"error": "No trades"}

    trades_df = pd.DataFrame(trades)

    return {
        "n_trades": len(trades),
        "win_rate": (trades_df["pnl_bps"] > 0).mean(),
        "avg_pnl_bps": trades_df["pnl_bps"].mean(),
        "std_pnl_bps": trades_df["pnl_bps"].std(),
        "total_pnl_bps": trades_df["pnl_bps"].sum(),
        "max_win_bps": trades_df["pnl_bps"].max(),
        "max_loss_bps": trades_df["pnl_bps"].min(),
        "tp_hit_rate": (trades_df["exit_reason"] == "TP_HIT").mean(),
        "sl_hit_rate": (trades_df["exit_reason"] == "SL_HIT").mean(),
        "sharpe": trades_df["pnl_bps"].mean()
        / trades_df["pnl_bps"].std()
        * np.sqrt(365 * 3)
        if trades_df["pnl_bps"].std() > 0
        else 0,
        "trades": trades_df,
    }


# Example usage
if __name__ == "__main__":
    # Create strategy
    config = RegimeFilterConfig(
        optimal_vol_regimes={0},  # Only low vol
        optimal_trend_regimes={1},  # Only trending
        take_profit_bps=50,
        stop_loss_bps=30,
        transaction_cost_bps=10,  # Maker fees
    )
    strategy = RegimeFilteredStrategy(config)

    # Example prediction
    from datetime import datetime

    preds = ModelPredictions(
        timestamp=datetime.now(),
        direction_pred=1,
        direction_prob=0.65,
        vol_regime_pred=0,
        vol_regime_prob=0.85,
        trend_regime_pred=1,
        trend_regime_prob=0.70,
    )

    signal = strategy.generate_signal(preds)
    print(f"Should trade: {signal.should_trade}")
    print(f"Direction: {signal.direction.name}")
    print(f"Confidence: {signal.confidence:.2f}")
    print(f"Reason: {signal.reason}")
    print(f"TP/SL: {signal.take_profit_bps}/{signal.stop_loss_bps} bps")

    if signal.should_trade:
        entry = strategy.create_entry(signal, 100000)  # BTC at 100k
        print(f"\nEntry: {entry.entry_price:.2f}")
        print(f"Take Profit: {entry.take_profit_price:.2f}")
        print(f"Stop Loss: {entry.stop_loss_price:.2f}")
