"""Structured RPF binary classification walk-forward internals."""

from regression_feature_engineering.walkforward.classification.cli import main
from regression_feature_engineering.walkforward.classification.data import (
    classification_score_rows,
    classification_numpy,
    classification_numpy_with_meta,
    load_joined_classification_batches,
)
from regression_feature_engineering.walkforward.classification.metrics import (
    DECISION_POLICIES,
    DECISION_POLICY_BATCH_TOPK_OFFLINE,
    DECISION_POLICY_CAUSAL_SIGNAL_BUDGET,
    DECISION_POLICY_THRESHOLD_ONLY,
    LIVE_SAFE_DECISION_POLICIES,
    binary_metrics,
    classification_objective,
    flatten_metrics,
    fmt_metric,
    matthews_corrcoef,
    none_to_bad,
    positive_probability,
    pr_auc_average_precision,
    select_decision_threshold,
    signal_predictions,
    stable_prediction_quality_score,
    stable_signal_quality_score,
    threshold_values,
    window_stability_constraints_reason,
    window_stability_metrics,
)
from regression_feature_engineering.walkforward.classification.model import fit_classifier, model_diagnostics
from regression_feature_engineering.walkforward.classification.runner import run_classification_windows
from regression_feature_engineering.walkforward.classification.targets import (
    DOWN_EXTREME,
    TARGET_BINARY_DOWN_2X_UP,
    TARGET_BINARY_DOWN_2X_UP_ALIAS,
    TARGET_BINARY_UP_2X_DOWN,
    TARGET_BINARY_UP_2X_DOWN_ALIAS,
    UP_EXTREME,
    binary_target_expr,
    canonical_binary_target_col,
    positive_rule_description,
    side_from_target,
)
from regression_feature_engineering.walkforward.policy import ELASTICNET_LOGISTIC_V1

__all__ = [
    "DOWN_EXTREME",
    "ELASTICNET_LOGISTIC_V1",
    "DECISION_POLICIES",
    "DECISION_POLICY_BATCH_TOPK_OFFLINE",
    "DECISION_POLICY_CAUSAL_SIGNAL_BUDGET",
    "DECISION_POLICY_THRESHOLD_ONLY",
    "LIVE_SAFE_DECISION_POLICIES",
    "TARGET_BINARY_DOWN_2X_UP",
    "TARGET_BINARY_DOWN_2X_UP_ALIAS",
    "TARGET_BINARY_UP_2X_DOWN",
    "TARGET_BINARY_UP_2X_DOWN_ALIAS",
    "UP_EXTREME",
    "binary_metrics",
    "binary_target_expr",
    "canonical_binary_target_col",
    "classification_objective",
    "classification_score_rows",
    "classification_numpy",
    "classification_numpy_with_meta",
    "fit_classifier",
    "flatten_metrics",
    "fmt_metric",
    "matthews_corrcoef",
    "load_joined_classification_batches",
    "main",
    "model_diagnostics",
    "none_to_bad",
    "positive_probability",
    "pr_auc_average_precision",
    "positive_rule_description",
    "run_classification_windows",
    "select_decision_threshold",
    "signal_predictions",
    "side_from_target",
    "stable_prediction_quality_score",
    "stable_signal_quality_score",
    "threshold_values",
    "window_stability_constraints_reason",
    "window_stability_metrics",
]
